### ISSUE TITLE
[iOS] Rich Notifications

### ISSUE THREAD

**Issue by khrichtchatyi** [Pushwoosh/pushwoosh-appcelerator-titanium#45]
Hello,
how to configure app for receive Rich Notifications?
by default my app doesn't show image in push notification.

**Comment by wfhm** [comment]
Hi,

Am I correct that you talk about iOS 10 Rich notifications? 

If so, this functionality is not yet available out of the box. Since Titanium does not save a native project after building, however still creates it during the process, it is theoretically possible to modify your native code to make media attachments work. 

The detailed guide on the integration process (a native one) can be found here:

http://docs.pushwoosh.com/docs/ios-10-rich-notifications-integration

You can access an XCode project as described [in this StackOverflow thread](https://stackoverflow.com/a/35261140/5408632).

**Comment by khrichtchatyi** [comment]
Thanks!
