### ISSUE TITLE
iOS10+ Media attachment	

### ISSUE THREAD

**Issue by macasfaj** [Pushwoosh/pushwoosh-appcelerator-titanium#46]
One question, can we use in Titanium Appcelerator iOS10+ Media attachment feature?

It would be great, but I can't find it in the documentation.

Thanks.

**Comment by shaders** [comment]
Hi please see this thread: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/45

The problem is that you need to add Notification Service Extension to the XCode project. However Titanium does not expose XCode project and preforms the build in background. See the thread above for the possible solution.
