### ISSUE TITLE
Titanium iOS - UIWebView deprecated

### ISSUE THREAD

**Issue by perdona** [Pushwoosh/pushwoosh-appcelerator-titanium#73]
Hi! PushWoosh module is keeping us from releasing an app to AppStore due to UIWebView deprecation. We need an updated version ASAP from you guys in order to be able to release our app.

**Comment by wfhm** [comment]
Hi @perdona,

Please let me pull some time to review the information that you have provided. We will get back to you soon.

**Comment by ygbr** [comment]
HI @wfhm should we also open a support ticket with Pushwoosh ? tks

**Comment by wfhm** [comment]
Hi @perdona

Yes, we are aware of `UIWebView` depreciation. It will be replaced with `WKWebView` in the nearest time. Work on it is almost done.
First, native SDKs will be updated in the coming days, and then we will immediately start updating plugins and other SDKs(including the Titanium SDK).

At the moment, the warning regarding `UIWebView` depreciation does not result in App Store rejections since it is not an error.
We will let you know as soon as the Titanium-iOS SDK is updated.

@ygbr no, we will notify you here as soon as the job is done.

**Comment by ygbr** [comment]
@wfhm any news on this? We are concerned since Apple can flip the switch any time by now.

**Comment by wfhm** [comment]
@ygbr the fix is already released for the native iOS SDK. The Titanium SDK will be updated in the nearest time. I will additionally notify you as soon as the new version is released. Thank you for your patience.

**Comment by wfhm** [comment]
@ygbr,

Fixed with the latest release.

**Comment by perdona** [comment]
But where are the files on release?

**Comment by wfhm** [comment]
@perdona

Here you can find the latest release of the Pushwoosh module:

https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/releases/tag/5.19.1

**Comment by perdona** [comment]
only the source code is available. Where are the compiled releases?

**Comment by wfhm** [comment]
@perdona

Indeed, you are correct. Just added them to the [current release](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/releases/tag/5.19.1).

Sorry for the inconvenience!

**Comment by perdona** [comment]
It's okay. Thanks a lot!
